version: '3.1'

services:

  db:
    image: postgres
    container_name: guerin-db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres

  tomcat:
    image: tomcat:latest
    container_name: guerin-app
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./target/guerin-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/guerin.war
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    environment:
      JAVA_VERSION: jdk-18.0.2
      CATALINA_BASE: /usr/local/tomcat
      CATALINA_HOME: /usr/local/tomcat
      CATALINA_TMPDIR: /usr/local/tomcat/temp
